id: I971D3B1A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:08:10+00:00'
last_modified: '2022-06-08T09:50:39.628561+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1302
  title: བར་དུ་དགེ་བའི་ཁྲིད་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B4EE:
      image_group_id: I1CZ1825
      title: Volume 1 of bar du dge ba'i khrid
      total_pages: 76
      order: 1
      base_file: B4EE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
