id: P006986
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1302
  title: བར་དུ་དགེ་བའི་ཁྲིད་
  author: ''
  volumes:
    b24d660337ee432f921a8dd89f32ea51:
      image_group_id: I1CZ1825
      title: ''
      volume_number: 1
      total_pages: 76
ebook_metadata:
  title: བར་དུ་དགེ་བའི་ཁྲིད་
  author: ''
  sku: P006986
  cover: cover.jpg
  layers:
  - pagination
